# add stages here 
stages:
  prepare_data:
    cmd: python src/stage_01_prepare.py
    deps:
      - src/stage_01_prepare.py
      - data/data.xml
      - src/utils/data_managment.py
      - configs/config.yaml
    params:
      - prepare.seed
      - prepare.split
    outs:
      - artifacts/prepared/train.tsv
      - artifacts/prepared/test.tsv